<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use GuzzleHttp\Promise\Create;

class PermintaanSeeder extends Seeder
{
    public function run()
    {
        DB::table('permintaans')->insert([
            [
                'nama_barang' => 'Pulpen Standard',
                'jumlah' => 10,
                'satuan' => 'pcs',
                'kode_barang' => 1,
                'keterangan_1' => 'Untuk kebutuhan harian',
                'keterangan_2' => '-',
                'keterangan_3' => '-',
                'id_verifikasi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Buku Catatan',
                'jumlah' => 19,
                'satuan' => 'pcs',
                'kode_barang' => 2,
                'keterangan_1' => 'Kebutuhan rapat',
                'keterangan_2' => '-',
                'keterangan_3' => '-',
                'id_verifikasi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Kertas Fotokopi',
                'jumlah' => 20,
                'satuan' => 'rim',
                'kode_barang' => 3,
                'keterangan_1' => 'Untuk kebutuhan umum',
                'keterangan_2' => 'Untuk printer umum',
                'keterangan_3' => '-',
                'id_verifikasi' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Stapler Kecil',
                'jumlah' => 10,
                'satuan' => 'pcs',
                'kode_barang' => 4,
                'keterangan_1' => 'Untuk kebutuhan kantor',
                'keterangan_2' => '-',
                'keterangan_3' => 'Pengganti alat rusak',
                'id_verifikasi' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Lem Kertas',
                'jumlah' => 5,
                'satuan' => 'pcs',
                'kode_barang' => 5,
                'keterangan_1' => 'Kebutuhan harian',
                'keterangan_2' => '-',
                'keterangan_3' => '-',
                'id_verifikasi' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Kertas Warna A4',
                'jumlah' => 20,
                'satuan' => 'rim',
                'kode_barang' => 6,
                'keterangan_1' => 'Untuk kebutuhan cetak',
                'keterangan_2' => 'Untuk cetak laporan',
                'keterangan_3' => '-',
                'id_verifikasi' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Spidol Marker',
                'jumlah' => 8,
                'satuan' => 'pcs',
                'kode_barang' => 7,
                'keterangan_1' => 'Untuk kebutuhan presentasi',
                'keterangan_2' => 'Digunakan saat presentasi',
                'keterangan_3' => '-',
                'id_verifikasi' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Kertas HVS A4',
                'jumlah' => 40,
                'satuan' => 'rim',
                'kode_barang' => 8,
                'keterangan_1' => 'Stok pengganti',
                'keterangan_2' => '-',
                'keterangan_3' => '-',
                'id_verifikasi' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Pensil HB',
                'jumlah' => 30,
                'satuan' => 'pcs',
                'kode_barang' => 9,
                'keterangan_1' => 'Untuk kebutuhan menggambar',
                'keterangan_2' => '-',
                'keterangan_3' => 'Untuk dokumentasi manual',
                'id_verifikasi' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Penggaris Plastik',
                'jumlah' => 10,
                'satuan' => 'pcs',
                'kode_barang' => 10,
                'keterangan_1' => 'Untuk kebutuhan pengukuran',
                'keterangan_2' => 'Untuk pelengkap alat tulis',
                'keterangan_3' => '-',
                'id_verifikasi' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_barang' => 'Spidol Permanen',
                'jumlah' => 15,
                'satuan' => 'pcs',
                'kode_barang' => 11,
                'keterangan_1' => 'Untuk penandaan dokumen',
                'keterangan_2' => '-',
                'keterangan_3' => '-',
                'id_verifikasi' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
